spring.application.name=mcp-github-lc4j

langchain4j.open-ai.chat-model.api-key=your_openai_api_key_here
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini
langchain4j.open-ai.chat-model.temperature=0.0



telusko.mcp.npx=npx.cmd
telusko.github.token=
logging.level.dev.langchain4j.mcp=DEBUG

