spring.application.name=mcp-client-app
langchain4j.open-ai.chat-model.api-key=your_openai_api_key_here
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini
langchain4j.open-ai.chat-model.temperature=0.0

telusko.mcp.server-jar=../mcp-server-java/target/telusko-mcp-server.jar
#telusko.mcp.server-jar=classpath:/mcp/telusko-mcp-server.jar


logging.level.dev.langchain4j.mcp=DEBUG
