spring.application.name=langchain-spring1
langchain4j.open-ai.chat-model.api-key=your_openai_api_key_here
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini
langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true

langchain4j.open-ai.chat-model.temperature=0.3

langchain4j.open-ai.chat-model.max-completion-tokens=500

langchain4j.open-ai.chat-model.timeout=PT30S

langchain4j.open-ai.chat-model.max-retries=2




